[package]
name = "r5ch"
version = "0.1.0"
authors = ["kgtkr <kgtkr.jp@gmail.com>"]

[dependencies]
hyper = "0.11"
serde_json = "1.0"
error-chain = "0.11"
rust-crypto = "^0.2"
rustc-serialize = "0.3"
native-tls = "0.1"
tokio-tls = "0.1"